resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '*.md'
    - LICENSE.txt
    - NOTICES.txt
  drafts: false

stages:
- stage: rcclStage
  displayName: 'RCCL develop PR'
  jobs:
  - deployment: rccl_pr_approval
    displayName: "CI Run Requires Approval"
    environment: rccl
  - job: rccl
    timeoutInMinutes: 180
    pool: rocm-ci_rccl_slurm_pool
    workspace:
      clean: all
    steps:
    - task: DeleteFiles@1
      inputs:
        Contents: '**/*'
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml@pipelines_repo
      parameters:
        submoduleBehaviour: recursive
    - template: templates/build.yml
    - template: templates/test_rccl-UnitTests.yml
    - template: templates/test_rccl-tests.yml
