name: TheRock Test Packages single-node

on:
  workflow_call:
    inputs:
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
      artifact_run_id:
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
      artifact_run_id:
        type: string

permissions:
  contents: read

jobs:
  test_rccl_single_node:
    name: 'Test single-node'
    runs-on: ${{ inputs.test_runs_on }}
    container:
      image: ghcr.io/rocm/no_rocm_image_ubuntu24_04@sha256:405945a40deaff9db90b9839c0f41d4cba4a383c1a7459b28627047bf6302a26
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --group-add 992
        --env-file /etc/podinfo/gha-gpu-isolation-settings
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      ARTIFACT_RUN_ID: "${{ inputs.artifact_run_id }}"
      OUTPUT_ARTIFACTS_DIR: "./build"
      THEROCK_BIN_DIR: "./build/bin"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "ROCm/TheRock"
          ref: f89dcd5c5625baecb467b9287e952c5c819073fd

      - name: Run setup test environment workflow
        uses: './.github/actions/setup_test_environment'
        with:
          ARTIFACT_RUN_ID: ${{ env.ARTIFACT_RUN_ID }}
          AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
          OUTPUT_ARTIFACTS_DIR: ${{ env.OUTPUT_ARTIFACTS_DIR }}
          VENV_DIR: ${{ env.VENV_DIR }}
          FETCH_ARTIFACT_ARGS: "--rccl --tests"
          IS_PR_FROM_FORK: ${{ github.event.pull_request.head.repo.fork }}

      - name: Test
        timeout-minutes: 15
        # Currently, TheRock CI in RCCL always builds with MPI-supported enabled which causes the
        # RCCL correctness tests to fail on the mi325 runners which don't have MPI pre-installed.
        # TODO (geomin12): Rebuild rccl-tests without MPI to enable RCCL correctness tests.
        run: |
          pytest ./build_tools/github_actions/test_executable_scripts/test_rccl.py -v -s \
            --log-cli-level=info \
            -k "not test_rccl_correctness_tests"
